### ISSUE TITLE
Topics comparison with inconsistent number of topics / date selection sliders

### ISSUE THREAD

**Issue by sunbrn** [FrInve/TETYS#3]
Here I selected 5 topics. 
Then, in the Topics temporal trends panel, I changed the Resolution from Monthly to 3 months, then to Yearly.
Every time I changed is, more time sliders kept appearing.

I would expect to see 5 lines in the plot with one unique date slider. Instead there are 4, it is not clear how they interact with each other nor why they are 4 instead of 5 (or... of 1!)

![image](https://github.com/user-attachments/assets/780ca5e8-9346-4e20-bf05-a63f979516e2)

**Comment by sunbrn** [comment]
I changed the time resolution to Yearly and the number of sliders has grown

![image](https://github.com/user-attachments/assets/1b5500fd-3c13-4b39-9de4-adf702b7dbbe)

**Comment by sunbrn** [comment]
Now I removed three of the 5 topics. Correctly, the corresponding lines in the plot are also removed, but the sliders remain.

![image](https://github.com/user-attachments/assets/b05821ca-40f8-48e7-b568-f5e88b52bf8e)

**Comment by amirsmv** [comment]
Hi, Thanks for reporting the issue. It's resolved and new changes have been pushed.
